name: Deploy to Railway

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run dummy CI checks
      run: |
        echo "Running CI checks..."
        python -c "print('✅ Python syntax check passed')"
        python -c "import sys; print(f'✅ Python version: {sys.version}')"
        echo "✅ All CI checks completed successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service backend
